### ISSUE TITLE
1.9 Dedicated server startup crash

### ISSUE THREAD

**Issue by xannor** [Liahim85/SaltyMod_1.8.9#1]
The following error occurs on startup of a dedicated server if SaltyMod is installed:

`Description: Exception in server tick loop                                                                                      │····················
                                                                                                                                │····················
net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: ru/liahim/saltmod/init/ModBlockColors            │····················
        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)                                     │····················
        at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)                                                 │····················
        at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102)                        │····················
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)                            │····················
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)                                │····················
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)                                                   │····················
        at java.lang.Thread.run(Thread.java:745)                                                                                │····················
Caused by: java.lang.NoClassDefFoundError: ru/liahim/saltmod/init/ModBlockColors                                                │····················
        at ru.liahim.saltmod.SaltMod.init(SaltMod.java:54)                                                                      │····················
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                          │····················
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                        │····················
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                │····················
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                     │····················
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)                          │····················
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)                                                          │····················
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                │····················
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                     │····················
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)                                      │····················
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)`

**Comment by Liahim85** [comment]
Update. Thank you for message.

**Comment by xannor** [comment]
Now I get a new error.
[http://pastebin.com/d7G5puxx](http://pastebin.com/d7G5puxx)

**Comment by Liahim85** [comment]
Update. Thanks a lot!

**Comment by TheOnlySilverClaw** [comment]
I think I'm getting basically the same error, as soon as I add Biomes of Plenty to a 1.8.9 server.

**Comment by Liahim85** [comment]
Can you send crash log?
